name: Docs

on:
  push:
    branches: [main]
    paths:
      - "apps/rebuild-docs/**"
      - "turbo.json"
      - "package.json"
      - "package-lock.json"
  pull_request:
    branches: [main]
    paths:
      - "apps/rebuild-docs/**"
      - "turbo.json"
      - "package.json"
      - "package-lock.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx turbo run build --filter=@mangolabs/pos-rebuild-docs
